### PR TITLE
Garo Assilian - UI/UX - Challenge 1 - Karaoke Needs Words

### PR DESCRIPTION
**Pull request by GaroAssilian**
**Starting up**
- After pulling project, `cd` into `ui/ux/challenge1`
- run `npm install` or `yarn`.
- run `npm start`
- url is in : `localhost:3000`

**Features**
- Takes the name of any artist and return top 10 songs from artist.
- Able to sort by track name, number of lyrics in song, and by artist name by clicking on appropriate row header.
- Re-clicking on same header will change sort order between ascending and descending.
- Can fetch 10 more results by clicking on the `Get more results` on the bottom of the track list. This will fetch another 10 songs.
- Clicking on any song will display the lyrics for that song. Clicking on same song again will hide lyrics.
- Making an empty search will return 10 random songs.

**Process**
I wanted to use React to develop this project, so I've used `create-react-app` to start it up. This allowed me to dive right into the development.
I've used `axios` in order to make the ajax calls to the MusixMatch API. Axios allows me to create a custom instance and define a base URL with header.
Generally, I would have the `apikey` hidden in a `dotenv` file, however I decided to forgo this step in order to make pulling and starting up the project easier.
Pursuant to the in-person tech interview, I decided to use `async await` for the calls to be API as I wanted to learn more about them.
For the CSS framework, I decided to go with Bootstrap and `reactstrap` as it offers great components to use for a React app such as this one.
All important files are found within the `src` folder. The `Components` folder contains all the React components and the `services` folder contains the API calls and the `AxiosInstance`.
In order to get the information I need whilst minimizing the API calls, I decided to use the `track.search` endpoint, and then use the `track.lyrics.get` endpoint. This allowed me to fetch all the required information for the project all at once. I only make more calls when the user wants to fetch more tracks to sing to. I also added a filter to get the most popular songs from an artist.

**Note**
This PR isn't actually 10K + lines long. Length is due to the `yarn.lock` file.

### CODE REVIEW

**Comment by tveronezi** [comment]
Hi @GaroAssilian ,
tx for taking the time for this challenge. You rock!

Can I ask a little bit more? 

* There are several warning messages on the console. Can you fix them?
* ReactJS has a "new way" of creating components with state without the use of classes. Can you follow the same pattern they have here: https://reactjs.org/docs/hooks-intro.html. Instead of using regular functions, use arrow functions.
* At byond we use jss instead of css. Can you try using that instead? https://cssinjs.org/react-jss/?v=v10.0.0-alpha.22
* Can you also trigger the search when the user hit `enter`?

**Comment by tveronezi** [comment]
Oh, can you also add a few tests?

**Comment by GaroAssilian** [comment]
@tveronezi Hey! 
Thank you for taking the time to review the challenge and for the feedback! I had fun building it and would love to improve upon it.
I was able to take a look at the React Hooks as well as JSS and am very excited to dive into them and integrate them into the project, they both look very interesting to use. I'll be making all of the other improvements as well.
Regarding a timeframe, I can have it done by the end of the day this Friday. Is this acceptable?

**Comment by GaroAssilian** [comment]
@tveronezi Hi,
I've just finished making all of the requested changes! Here are some notes about what was done and as well as some improvements I can make in the future:

**Changes**
- Enter button will now trigger search. As long as the search is being made, user cannot make another search.
- All react components are now functions and use the `useState` React hook.
- Integrated JSS into project. npm currently only have version `8.6.1` so I have decided to work with this stable version. Pursuant to this, moved all styles to the `styles.js` file and deleted the `.css` file.
- Removed duplicate key console errors -- problem was that the `Get More Results` and `Search` button did not behave in the same way.
- Wrote tests for all components. They can be found in the `Tests` folder under `src`. I used AirBnB's `enzyme` in order to write my tests. All tests can be run by running `npm test` within the `challenge-1` folder.

**NOTES / IMPROVEMENTS**
- Due to components now being functions and using the new React Hooks for the state, the tests were a little tricky to get right since Enzyme could no longer access the state. After some research, what I did to resolve this issue was to mock the `useState` hook within the tests and then check to see if the `setState` method had been called with the correct values.
- I wanted to test the axios calls as well using `axios-mock-adapter`, however I was having a bit of trouble with it.
- I looked at other testing frameworks such as `react-testing-library` (https://github.com/testing-library/react-testing-library). I wanted however to dig deeper using enzyme to figure out how I can make it work with the React Hooks.

**Comment by GaroAssilian** [comment]
Hi again!
I had forgotten to mention to run `yarn` or `npm install` prior to starting up the project as I have added new dependencies.

**Comment by tveronezi** [comment]
tx!

**Pull request closed without merging**
