### PR TITLE
Moody cats

### PR DESCRIPTION
**Pull request by lcoderre**
👋 Hi all, here's my small* solution to the Challenge 4, the moody cats.

 \* I left my thoughts in the README. My dislikes, the direction I was headed to (if I had more time on my hands), and quick steps to run the solution

It was a very fun challenge, quite educating ;-) 
Thanks.

### CODE REVIEW

**Comment by soujiro32167** [comment]
Thanks for the PR, Laurens! This is good stuff, especially since you've just tackled `Akka` and `Spark`

Suppose you had the ideal architecture you've described with Kafka and docker compose. How would you scale the system horizontally across machines? That is, how would you get linear increase in throughput going from 1 machine to 2

**Comment by lcoderre** [comment]
Hey Eli,
In this particular example, the generator part is independent and could easily generate a ton of moods on its own. This is probably not the part I would scale first.

I would try to scale up the messaging queue and the spark processing. 

Technically, to actually split some processing off to a new machine, I could do that by configuring both machines as docker nodes, and describing the `services:` in the `docker-compose.yml` as multiple kafka nodes, for example. The docker swarm manager would take care of creating a new Kafka task on the available resources (other machine). I can do that for any component of my system, as long as that component is stateless, I think.

If I understand correctly, a Kafka cluster is smart enough to auto-distribute the load by assigning nodes to specific partitions for certain topics. So the scaling of the message queue should be pretty straightforward, especially since all nodes would work on the same topic.

The part I honestly do not grasp yet, is how the spark side scales. Documentation indicates it does, but I don’t yet see how the parallel computing of stats from a Kafka stream could be collected (as the latest aggregate) and dumped in a database. It looks as if I would need to have only one SparkSession, but multiple workers. 

At this point, this is pure assumption, and would need to spend time trying it out because the details are unclear 🙂

**Comment by sergei-shabanau** [comment]
@lcoderre Thanks for the PR!

I'd like to mention the following points I really liked:
1. The simplicity of the solution
2. The readme with problematic points already identified
3. Clean code 

I understand you have limited exposure to Scala, but I see you took a lot of effort to delve into (rather complex) akka-streams and spark, thanks!

A question: what would be your approach to study world population of cats, specifically, how would you go about simulating mood swings of such a big herd?

**Comment by soujiro32167** [comment]
Kafka scaling goes deep - in general as you have described. Spark also has fascinating scaling parameters. Thanks for the answer @lcoderre

**Comment by lcoderre** [comment]
Hey Sergei! 👋 Thanks for your comments :-)

If we're dealing with real world cyborg cats that have mood sensors... Then the distribution of moods won't necessarily be the same as my Random(1..8). 

I could determine the actual distribution by looking at the total moods count aggregate, similar to the logic I already put in place in my small solution.

We could also have a sampler service that consumes the topic with random moods up to a relevant sample size, and find the distribution of that sample.

Then, once you know the distribution, I assume you could simulate any amount of data you'd like, as long as the randomness follows that distribution...

Depending what kind of studies you'd like to do - _I really don't know why people love cats that much_ - there are other tools that could help. For example, we could be keeping around the data of the last couple days, and always analyzing based on 2 days-old datasets, etc.

Of course, here I thought of the statistical challenge of dealing with actual "huge real world data sample", but I assume there are other technical challenges related to big data. One that fascinates me is how we'll keep storing data for the next years :P

**Pull request closed without merging**
