### PR TITLE
uiux-1 solution api client

### PR DESCRIPTION
**Pull request by dipeshwalia**

### CODE REVIEW

**Comment by dipeshwalia** [comment]
branch level view https://github.com/dipeshwalia/amaze-us/tree/dipesh

**Comment by tveronezi** [comment]
Hi @dipeshwalia ,

Thank you very much for taking the time to play along with the code challenge. 

Can we try something? Would you mind changing the styles of your application a bit?

* make the page look like a google search: 
  * one field at the middle of the page. 
  * when the user searches something, the search box goes to the top and a list of links goes after it.
  * the footer of the page stays at the bottom of the page, but it can change position if the list is too big to show all the links and the footer in the same viewport.
* make sure the search is triggered by:
  * clicking the search button 
  * hitting the `enter` key

**Comment by dipeshwalia** [comment]
sure, expect this to be done on or before April 28. Thanks for update.

**Comment by bruno-morel** [comment]
Closing this. Thank you very much

**Pull request closed without merging**
