### PR TITLE
Aly Gueye - microservice/challenge-1 SuiteCRM

### PR DESCRIPTION
**Pull request by alygueye**
Hello,
This is my submit for the microservice/challenge-1.
Please check [README.md](https://github.com/alygueye/amaze-us/tree/alygueye/microservice/challenge-1/suitecrm/README.md) for detailed instructions
I hope you will enjoy.
Have a nice day.
Thanks

### CODE REVIEW

**Comment by scoquelin** [comment]
@alygueye can you please fix the test datasets in `csv-ingester` as they are currently showing as `.emptyFile` for some reason and therefore unit tests are failing... thanks !

**Comment by alygueye** [comment]
@scoquelin Thank you for reviewing
I tested it on another computer and I notice that I omited to commit the directory [_ingester_samples](https://github.com/alygueye/amaze-us/tree/alygueye/microservice/challenge-1/suitecrm/csv-ingester/src/test/resources/datasets/_ingester_samples) under src/test/resources/datasets .
This directory contain samples csv used by the tests, thats why ingester tests fails.

PS: the .emptyFile was added by me to verify that the app doesn't start ingest existing files on startup

**Comment by scoquelin** [comment]
@alygueye thanks for fixing the build, `mvn clean install` is green now
We are in the process of reviewing the code. Great work so far.

However there are a couple of issues while executing the steps you provided.
I managed to somehow workaround them but I would please ask you to fix/document them and proof-test the final version of your PR.

1) The docker network used is not consistent everywhere causing the `kafka` host not being visible from csv-ingester and kafka-processing apps for example...

2) In the instructions provided in the  `README.md`, copying the sample datasets results in files being copied as `root` and therefore ingestion fails because of the rights of the file.

```
ingester               | 2019-02-07 19:12:46.848 678426 [main] INFO  c.c.s.i.IngestionWatcherService - dataPath : /datasets/PRODUCTS/ingest_products.csv
ingester               | 2019-02-07 19:12:46.848 678426 [main] INFO  c.c.s.i.IngestionWatcherService - Data file /datasets/PRODUCTS/ingest_products.csv detected and put in processing buffer.
ingester               | 2019-02-07 19:12:46.849 678427 [main] INFO  c.c.s.i.IngestionWatcherService - Waiting file lock on /datasets/PRODUCTS/ingest_products.csv
ingester               | 2019-02-07 19:12:46.849 678427 [main] ERROR c.c.s.i.IngestionWatcherService - Ingesting of file /datasets/PRODUCTS/ingest_products.csv failed.
ingester               | java.io.FileNotFoundException: /datasets/PRODUCTS/ingest_products.csv (Permission denied)
ingester               | 	at java.io.RandomAccessFile.open0(Native Method)
ingester               | 	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
ingester               | 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
ingester               | 	at com.challenge.suitecrm.ingester.IngestionWatcherService.waitToFileLock(IngestionWatcherService.java:208)
ingester               | 	at com.challenge.suitecrm.ingester.IngestionWatcherService.processDatafile(IngestionWatcherService.java:177)
ingester               | 	at com.challenge.suitecrm.ingester.IngestionWatcherService.handleCreateEntry(IngestionWatcherService.java:141)
ingester               | 	at com.challenge.suitecrm.ingester.IngestionWatcherService.run(IngestionWatcherService.java:117)
ingester               | 	at com.challenge.suitecrm.ingester.IngestionWatcherCommand.runDirectoryWatcher(IngestionWatcherCommand.java:54)
ingester               | 	at com.challenge.suitecrm.ingester.IngestionWatcherCommand.run(IngestionWatcherCommand.java:40)
ingester               | 	at com.challenge.suitecrm.ingester.IngestionWatcherCommand.main(IngestionWatcherCommand.java:33)
```

3) Please provide instructions to connect to Cassandra and list the mentioned tables

Thanks!

**Comment by alygueye** [comment]
@scoquelin Thanks again, i'm really sorry that you have these issues.
1. I add `.env` files (anothers ignored files during my commit), this will force docker-compose to create/or use the correct network.

2. To avoid "Permission denied" on the datasets, i update the ingester Docker file et added this environnement variable on the compose file:
   ```yaml
     ingester:
       image: suitecrm/csv-ingester:latest
       container_name: ingester
       hostname: ingester
       environment:
          - UID_USER=${ID}
       volumes:
          - $PWD/csv-ingester/target/test-classes/datasets:/datasets
       command:
          -d /datasets
   ``` 
3. You can see in the `README.md` instructions to connect to Cassandra

PS: I run all this using a Macbook computer

Thank you, and feel free to contact me if you have any question/issues/etc ...

**Comment by bruno-morel** [comment]
closing this for clean up. All good! Thanks a lot! See you soon! :)

**Pull request closed without merging**
