### PR TITLE
karaoke solution

### PR DESCRIPTION
**Pull request by tveronezi**
What's in the box:
* It comes with an easy simple command startup. (More in the README.adoc file).
* Application based on Angular5, Webpack4, JavaEE with TomEE. Implemented with Typescript, SASS, Pug, Java and Groovy.
* Only depends on Maven and Docker. No need to install NodeJs.
* Ready to scale with Docker.

Missing bits:
* not sorting by lyrics size
* missing unit tests (theres only place holders for frontend and backend tests)
* missing functional tests with cucumber

### CODE REVIEW

**Comment by tveronezi** [comment]
* Added unit tests for the backend.
* Added starting point for the functional tests with arquillian cube

**Comment by tveronezi** [comment]
* added server side rendering

**Comment by bruno-morel** [comment]
Hey Thiago, 

Great start.
Can you do a bit of the front work to show us how amazing you can be at making something cute ? Not to do a full design, just getting into some basic UX work if you can :)

Tks!

**Comment by tveronezi** [comment]
Hi Bruno,
I will try adding something tonight.
Tx.

**Comment by tveronezi** [comment]
@bruno-morel haha! :) Yeah. I had a busy week. Asked Galyna to forward a message before reading this one from you. 

Just pushed a commit with eye candy changes. 

It contains:

* angular material,
* infinite scroll 
* moment

**Comment by bruno-morel** [comment]
Thanks Thiago...I'm closing this but you'll hear from us :P

**Pull request closed without merging**
