### PR TITLE
Amaze us Sarath

### PR DESCRIPTION
**Pull request by srth12**

### CODE REVIEW

**Comment by albertaouad** [comment]
@srth12 thank you for your submission, we will be looking at your PR during the upcoming days and leaving you some feedback or questions. Please address it accordingly.

**Review by alygueye — CHANGES_REQUESTED** [review]
Hi @srth12 thanks for the PR and the effort.
I have 2 small comments:
- Can you please provide a doc/readme that explain the solution and how the services interact together
- I didnt see any tests (units or integration, ...), is it possible to provide some tests
Thank you

**Comment by srth12** [comment]
@alygueye I have crated couple of tests and updated the `README.md` file in the location `microservice/challenge-3/README.md` with how the application is working. Due to busy schedule, I couldn't include the design diagrams.

**Comment by alygueye** [comment]
> @alygueye I have crated couple of tests and updated the `README.md` file in the location `microservice/challenge-3/README.md` with how the application is working. Due to busy schedule, I couldn't include the design diagrams.

Thank you @srth12 , no worries for the design diagrams, the readme file should be ok.

**Comment by albertaouad** [comment]
Closing this PR

**Pull request closed without merging**
