### PR TITLE
Feature/challenge3

### PR DESCRIPTION
**Pull request by BreakpointsCA**
Working solution
**Author**: Mathieu Pelletier 2021
**Email**: mathieu.pelletier@breakpoints.ca

### CODE REVIEW

**Comment by lucasledesma** [comment]
Hi Mathieu. Thanks for taking the time to put together this PR.
Question:
When I start the different containers using the docker-compose file as instructed I get the solution to work (partially?) but I am seeing the following issues in the logs:
* An exception because of this -> "Table 'tweets_analysis.retweets' doesn't exist"
* This other message -> mbind: Operation not permitted
Do you see them on your side? 
If so, can you explain why they happen? 
And if applies, how they should be fixed?
Thanks!

**Comment by BreakpointsCA** [comment]
Hello @lucasledesma ,

Seems to be an issue with Mysql and Docker. https://thegeekbin.com/mbind-operation-not-permitted-docker-mysql/
I use a setting in docker-compose to fix that.

Are you running on a Linux or Mac?
On Windows 10, I don't have this issue.

If it still doesn't work, I will try a different mysql version.

**Comment by lucasledesma** [comment]
Hello Mathieu,

I am using mac.
Yes, I saw the same thing about "Operation not permitted" problem.

What about the other issue? I am getting an exception when running the app.

part of the logs:

`dashboard_1          | pymysql.err.ProgrammingError: (1146, "Table 'tweets_analysis.retweets' doesn't exist")
dashboard_1          | 172.23.0.1 - - [29/Sep/2021 14:10:23] "GET /data?graph=chartTotalRetweets HTTP/1.1" 500 -
dashboard_1          | [2021-09-29 14:10:23,242] ERROR in app: Exception on /data [GET]
dashboard_1          | Traceback (most recent call last):
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 2317, in wsgi_app
dashboard_1          |     response = self.full_dispatch_request()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1840, in full_dispatch_request
dashboard_1          |     rv = self.handle_user_exception(e)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1743, in handle_user_exception
dashboard_1          |     reraise(exc_type, exc_value, tb)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 36, in reraise
dashboard_1          |     raise value
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1838, in full_dispatch_request
dashboard_1          |     rv = self.dispatch_request()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1824, in dispatch_request
dashboard_1          |     return self.view_functions[rule.endpoint](**req.view_args)
dashboard_1          |   File "app.py", line 182, in get_graph_data
dashboard_1          |     return jsonify(get_data(graph))
dashboard_1          |   File "app.py", line 108, in get_data
dashboard_1          |     cursor.execute(WORST_CITIES_QUERY)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 170, in execute
dashboard_1          |     result = self._query(query)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 328, in _query
dashboard_1          |     conn.query(q)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 517, in query
dashboard_1          |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 732, in _read_query_result
dashboard_1          |     result.read()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 1075, in read
dashboard_1          |     first_packet = self.connection._read_packet()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 684, in _read_packet
dashboard_1          |     packet.check_error()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/protocol.py", line 220, in check_error
dashboard_1          |     err.raise_mysql_exception(self._data)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
dashboard_1          |     raise errorclass(errno, errval)
dashboard_1          | pymysql.err.ProgrammingError: (1146, "Table 'tweets_analysis.retweets' doesn't exist")
dashboard_1          | 172.23.0.1 - - [29/Sep/2021 14:10:23] "GET /data?graph=chartWorstCities HTTP/1.1" 500 -
dashboard_1          | 172.23.0.1 - - [29/Sep/2021 14:10:24] "GET / HTTP/1.1" 200 -
dashboard_1          | 172.23.0.1 - - [29/Sep/2021 14:10:24] "GET /data?graph=chartTotalTweets HTTP/1.1" 200 -
dashboard_1          | [2021-09-29 14:10:24,960] ERROR in app: Exception on /data [GET]
dashboard_1          | Traceback (most recent call last):
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 2317, in wsgi_app
dashboard_1          |     response = self.full_dispatch_request()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1840, in full_dispatch_request
dashboard_1          |     rv = self.handle_user_exception(e)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1743, in handle_user_exception
dashboard_1          |     reraise(exc_type, exc_value, tb)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 36, in reraise
dashboard_1          |     raise value
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1838, in full_dispatch_request
dashboard_1          |     rv = self.dispatch_request()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1824, in dispatch_request
dashboard_1          |     return self.view_functions[rule.endpoint](**req.view_args)
dashboard_1          |   File "app.py", line 182, in get_graph_data
dashboard_1          |     return jsonify(get_data(graph))
dashboard_1          |   File "app.py", line 103, in get_data
dashboard_1          |     cursor.execute(RETWEETS_QUERY)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 170, in execute
dashboard_1          |     result = self._query(query)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 328, in _query
dashboard_1          |     conn.query(q)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 517, in query
dashboard_1          |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 732, in _read_query_result
dashboard_1          |     result.read()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 1075, in read
dashboard_1          |     first_packet = self.connection._read_packet()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 684, in _read_packet
dashboard_1          |     packet.check_error()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/protocol.py", line 220, in check_error
dashboard_1          |     err.raise_mysql_exception(self._data)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
dashboard_1          |     raise errorclass(errno, errval)
dashboard_1          | pymysql.err.ProgrammingError: (1146, "Table 'tweets_analysis.retweets' doesn't exist")
dashboard_1          | 172.23.0.1 - - [29/Sep/2021 14:10:24] "GET /data?graph=chartTotalUsers HTTP/1.1" 200 -
dashboard_1          | [2021-09-29 14:10:24,964] ERROR in app: Exception on /data [GET]
dashboard_1          | Traceback (most recent call last):
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 2317, in wsgi_app
dashboard_1          |     response = self.full_dispatch_request()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1840, in full_dispatch_request
dashboard_1          |     rv = self.handle_user_exception(e)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1743, in handle_user_exception
dashboard_1          |     reraise(exc_type, exc_value, tb)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 36, in reraise
dashboard_1          |     raise value
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1838, in full_dispatch_request
dashboard_1          |     rv = self.dispatch_request()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1824, in dispatch_request
dashboard_1          |     return self.view_functions[rule.endpoint](**req.view_args)
dashboard_1          |   File "app.py", line 182, in get_graph_data
dashboard_1          |     return jsonify(get_data(graph))
dashboard_1          |   File "app.py", line 108, in get_data
dashboard_1          |     cursor.execute(WORST_CITIES_QUERY)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 170, in execute
dashboard_1          |     result = self._query(query)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 328, in _query
dashboard_1          |     conn.query(q)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 517, in query
dashboard_1          |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 732, in _read_query_result
dashboard_1          |     result.read()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 1075, in read
dashboard_1          |     first_packet = self.connection._read_packet()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 684, in _read_packet
dashboard_1          |     packet.check_error()
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/protocol.py", line 220, in check_error
dashboard_1          |     err.raise_mysql_exception(self._data)
dashboard_1          |   File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
dashboard_1          |     raise errorclass(errno, errval)
dashboard_1          | pymysql.err.ProgrammingError: (1146, "Table 'tweets_analysis.retweets' doesn't exist")`

**Comment by BreakpointsCA** [comment]
Hello,

Yes, I think I know why even if I didn't experience it myself. Like I mentioned in the README, I had issues with the retweets. I didn't see any tweets with the retweet flag on. So the retweets table is never created as the dataframe is always empty in metrics generator. I fixed the issue by creating a database initialization script. Before that, Spark was responsible to create the table at writing time.

Thanks,
Mathieu

**Pull request closed without merging**
