### PR TITLE
challenge 1 - spring 

### PR DESCRIPTION
**Pull request by magg**

### CODE REVIEW

**Comment by albertaouad** [comment]
Hi @magg ,

Can you please provide us with which java version this application is supposed to work.
Also how do we run this application, your README only includes how to compile/build  but doesnt mention how to start this application.

**Comment by magg** [comment]
Done, I have updated the read.me with instructions on how to run and which java version I used

regards

**Comment by albertaouad** [comment]
@magg another question for you, can you please explain the boundaries for each microservice and how can I scale this application with the setup u provided me.

I'd also like to see some tests in your challenge, as we previously explained, the aim was not to finish but to showcase your skillset by writing code, tests, infrastructure code (a better compose to spin up those services, instead of using gradle ?!? ), documentation.
You can always stop at the level u presented, and we will make our decision based on that content if you think it is enough to get an overview of all the skills u have.

**Comment by magg** [comment]
Ok I can work on all of that, so this means I can have more time to work on it?

**Comment by albertaouad** [comment]
> 
> 
> Ok I can work on all of that, so this means I can have more time to work on it?

It's honestly up to u, when we sent u the challenge we clearly communicated that you can take as much time as u want as long as u think you showed us enough of your amazing skills.
You can say that's all I am going to present, or you can say, well I am going to take a couple more days to actually make this solution amaze you (B-Yond).

I repeat do as much as you think it is necessary for us to be amazed.

**Comment by magg** [comment]
Ok I will take a few days to work on this, sorry for the misunderstanding...

**Comment by magg** [comment]
Hi @albertaouad , I have updated my code, please have a look... I have included Docker files and docker compose, added a test suite for all projects, included some documentation

**Pull request closed without merging**
