### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ghewachall**
Ghewa Al Chall Challenge 1

### CODE REVIEW

**Comment by sajid-austria-byd** [comment]
Hello @ghewachall  thank you for submitting your PR  , We have some questions ...

1. What stack do you use and why ?	
2. Could you elaborate on your ETL process from CSV to database , how could it be automated  ?
3. Could you push the DDL statements used and all other information related to the data modeling and explain your decisions ? 
4. How would you write a test for these reports  ?
5. How the reports would be impacted in terms of performance if the data grows from hundreds of records  to hundreds of millions of records ?
6. If the data grew , what would be the pain points in the last report `Number of Gold,Silver, Bronze for every country that has at least one medal of any kind` , and how would you solve it  ?

**Comment by abed-sinno-byd** [comment]
Hello @ghewachall, thanks as well, I'd like to clarify although about the preferred submission for this challenge: we like to see a runnable/testable solution; which can include the steps or DDL to step up the database schema, but also preferably an application for allowing data to be provided/added and queries to be made.

**Comment by ghewachall** [comment]
Hello Abed,
Thank you for your reply. 
Honestly, I faced an issue in finding a free software to write and implement the SQL queries. In my current job, we use Oracle SQL developer and ODI, but I can’t use them for personal purposes. The only software, which worked smoothly for a couple of days was DBeaver, which has a flexible easy way to import data from excel to tables and create a schema on a testing database. However, I can add the DDL statement to the SQL file if you don’t have any problem with this approach. Please, let me know your thoughts or if you recommend using any other free stack. Your help is appreciated.

Thank you for understanding.

**Comment by ghewachall** [comment]
Hello Sajid,

Thank you for your reply.
Regarding the stack, as I mentioned Dbeaver was a free accessible software to use in order to write the SQL and run them on a testing database because of this I went with this approach. 
To import data, I used Dbeaver easy way to create tables and import csv in them. For work purposes, we can use a stack to import csv automatically to the database. Example is the Oracle Data Integrator. For this exercise, the data model consisted of 5 tables, where each table represents the excel file. No data was cleaned or removed because there was no need to do this. 
I can add the DDL statements to the SQL file if this is suitable for you and Abed.
The performance of the SQL queries will for sure be affected when the data grows. There are ways that can be used to maintain the same performance. Example of these ways: including index fields in the where clauses, which reduces the processing times and removing functions from  join clauses like trim function for example.
Adding the medal as an index to the summer games table can help in maintaining the performance of the report with large number of data. 

Hope this answers your questions.
I am waiting your response with Abed's response to add the DDL statements to the sql file.

Best,

**Pull request closed without merging**
