### PR TITLE
Add kepler colony prototype - Challenge 2 UIUX

### PR DESCRIPTION
**Pull request by sylhare**
Hi,

Here is a prototype for the Kepler app, I was new to React for the frontend, but since it's good for single page app and you are using it, I figured I might as well learn that.
I scale the project to deal with the amount of population, making baby requests, listing them and approving denying them.

Each app has a set of tests that are run in the github action pipeline.

I hope you will be able to find all you need in the README of each apps, if you have any question, let me know.

### CODE REVIEW

**Comment by albertaouad** [comment]
@sylhare, thanks to your great work we are now able to grow our population in Domy-Neon 👶 
For some reason, every time our application crashes (every day) we seem to lose track of our baby requests, on top of that our Auditor General 🤓  always inspects approved baby requests, and since upgrading to the latest software, he was unable to see who approved what and when 🕵️ .

We look for your contribution to help the people of Domy-Neon 👨‍🚀  to thrive 🚀 .

**Comment by sylhare** [comment]
Alright, I'll work on that :+1:

**Comment by sylhare** [comment]
Domy-Neon people 👩‍🚀👩‍🚀, you have been heard! I hope that this contribution will address your needs.
I have added a Mongo db for persistent storage of the baby request, as well as a login feature to keep track of who does what and finally a brand new page to audit and look into the approved request.

@albertaouad it's ready for review 👍

**Comment by albertaouad** [comment]
@sylhare, the people of domy-neon are grateful for what you've offered them, their population has been growing under control ad our auditor general is very happy with the new toolset he has.
They reached out directly to us and recommended you to be part of our team.
We will close this PR and get HR to contact you to move forward.

**Pull request closed without merging**
